// Auto-generated by scripts/generate-solar-icons.cjs
// Shared solar-icons runtime (no icon SVG data). DO NOT EDIT MANUALLY.
/* eslint-disable @typescript-eslint/no-explicit-any */

import { defineComponent, computed, h, inject, provide, reactive, Fragment, type Component } from 'vue';

export const DEFAULT_CONTEXT = { color: 'currentColor', size: '24', weight: 'Linear', mirrored: false } as const;
export const SOLAR_ICONS_CONFIG_KEY = Symbol.for('solar-icons-config');
const DEFAULT_SOLAR = { config: DEFAULT_CONTEXT, setConfig: () => {}, setWeight: () => {}, setSize: () => {}, setColor: () => {} };

export function useSolar() {
  return inject(SOLAR_ICONS_CONFIG_KEY, DEFAULT_SOLAR) as typeof DEFAULT_SOLAR;
}

export function provideSolarIconsContext(ctx: any) {
  provide(SOLAR_ICONS_CONFIG_KEY, ctx);
}

export const SvgNodeRenderer: Component = defineComponent({
  name: 'SvgNodeRenderer',
  props: { node: { type: Array, required: true } },
  setup(props) {
    return () => {
      const node = props.node as any[];
      const tag = node[0] as string;
      const attrs = node[1] as Record<string, any>;
      const children = (node[2] || []) as any[];
      return h(tag as any, attrs, children.map((child: any, idx: number) =>
        h(SvgNodeRenderer as any, { key: idx, node: child })
      ));
    };
  }
}) as any;

export const SolarIcon: Component = defineComponent({
  name: 'SolarIcon',
  props: {
    iconNodes: { default: () => [] as any[] },
    color: {},
    size: {},
    mirrored: { type: Boolean },
    alt: {},
  },
  setup(props: any) {
    const { config } = useSolar();
    const resolvedColor = computed(() => props.color ?? config.color ?? DEFAULT_CONTEXT.color);
    const resolvedSize = computed(() => props.size ?? config.size ?? DEFAULT_CONTEXT.size);
    const resolvedMirrored = computed(() => props.mirrored || config.mirrored || DEFAULT_CONTEXT.mirrored);

    return (vm: any) => h('svg', {
      xmlns: 'http://www.w3.org/2000/svg',
      width: resolvedSize.value,
      height: resolvedSize.value,
      color: resolvedColor.value,
      fill: 'none',
      viewBox: '0 0 24 24',
      transform: resolvedMirrored.value ? 'scale(-1, 1)' : undefined,
      ...vm.$attrs,
    }, [
      props.alt ? h('title', null, props.alt) : null,
      ...(props.iconNodes as any[]).map((node: any, idx: number) =>
        h(SvgNodeRenderer as any, { key: idx, node })
      ),
    ]);
  }
}) as any;

export function createIcon(name: string, weights: Record<string, any[]>): Component {
  return defineComponent({
    props: { weight: {} },
    setup(props, { attrs, slots }) {
      const { config } = useSolar();
      const weightKey = computed(() => (props as any).weight ?? config.weight ?? DEFAULT_CONTEXT.weight);
      const nodes = weights[weightKey.value] || weights['Linear'] || [];
      return () => h(SolarIcon as any, { ...attrs, ...(props as any), iconName: name, iconNodes: nodes }, slots);
    }
  }) as any;
}

export const SolarProvider = defineComponent({
  name: 'SolarProvider',
  props: {
    color: { default: 'currentColor' },
    size: { default: '1em' },
    weight: { default: 'Linear' },
    mirrored: { type: Boolean, default: false },
  },
  setup(props: any) {
    const ctx = reactive({
      color: props.color,
      size: props.size,
      weight: props.weight,
      mirrored: props.mirrored,
    });
    provideSolarIconsContext(ctx);
    computed(() => {
      ctx.color = props.color;
      ctx.size = props.size;
      ctx.weight = props.weight;
      ctx.mirrored = props.mirrored;
    });
    return (vm: any) => h(Fragment, null, vm.$slots.default?.());
  }
});
