import { describe, expect, it } from "vitest";
import {
  getLauncherItemBadgeText,
  getLauncherUrlKind,
  getScannedLaunchCommandTarget,
  getScannedLaunchType,
  getScannedLauncherUrl,
  normalizeScannedLaunchKey,
} from "../scanned-app-launch";

describe("scanned-app-launch", () => {
  it("uses resolved target paths for file launch entries", () => {
    const entry = {
      name: "15 Bands Graphic EQ",
      path: "{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\\VB\\Voicemeeter\\VoicemeeterBUSGEQ15.exe",
      targetPath: "C:\\Program Files (x86)\\VB\\Voicemeeter\\VoicemeeterBUSGEQ15.exe",
      launchType: "file" as const,
      source: "应用目录",
      publisher: null,
      iconBase64: null,
    };

    expect(getScannedLaunchType(entry)).toBe("file");
    expect(getScannedLaunchCommandTarget(entry)).toBe(
      "C:\\Program Files (x86)\\VB\\Voicemeeter\\VoicemeeterBUSGEQ15.exe",
    );
    expect(normalizeScannedLaunchKey(entry)).toBe(
      "c:/program files (x86)/vb/voicemeeter/voicemeeterbusgeq15.exe",
    );
  });

  it("keeps AppsFolder AUMIDs as shell launch targets", () => {
    const entry = {
      name: "Codex",
      path: "shell:AppsFolder\\OpenAI.Codex_2p2nqsd0c76g0!App",
      launchType: "shell" as const,
      source: "应用目录",
      publisher: null,
      iconBase64: null,
    };

    expect(getScannedLaunchType(entry)).toBe("shell");
    expect(getScannedLaunchCommandTarget(entry)).toBe(
      "shell:AppsFolder\\OpenAI.Codex_2p2nqsd0c76g0!App",
    );
  });

  it("keeps steam links as protocol launch targets", () => {
    const entry = {
      name: "Infinitode 2",
      path: "steam://rungameid/937310",
      launchType: "protocol" as const,
      source: "应用目录",
      publisher: null,
      iconBase64: null,
    };

    expect(getScannedLaunchType(entry)).toBe("protocol");
    expect(getScannedLaunchCommandTarget(entry)).toBe("steam://rungameid/937310");
  });

  it("treats legacy AppsFolder bare IDs as shell launch targets", () => {
    const entry = {
      name: "Database Compare",
      path: "Microsoft.Office.DATABASECOMPARE.EXE.15",
      source: "应用目录",
      publisher: null,
      iconBase64: null,
    };

    expect(getScannedLaunchType(entry)).toBe("shell");
    expect(getScannedLaunchCommandTarget(entry)).toBe("Microsoft.Office.DATABASECOMPARE.EXE.15");
    expect(getScannedLauncherUrl(entry)).toBe("shell:AppsFolder\\Microsoft.Office.DATABASECOMPARE.EXE.15");
  });

  it("labels shell app URLs separately from normal web URLs", () => {
    expect(getLauncherUrlKind("shell:AppsFolder\\Microsoft.AutoGenerated.{A49227EA-5AF0-D494-A3F1-0918A278ED71}")).toBe("app");
    expect(getLauncherItemBadgeText({
      itemType: "url",
      url: "shell:AppsFolder\\OpenAI.Codex_2p2nqsd0c76g0!App",
    })).toBe("应用");
  });

  it("labels protocol launch URLs separately from normal web URLs", () => {
    expect(getLauncherUrlKind("steam://rungameid/937310")).toBe("protocol");
    expect(getLauncherItemBadgeText({
      itemType: "url",
      url: "steam://rungameid/937310",
    })).toBe("协议");
    expect(getLauncherItemBadgeText({
      itemType: "url",
      url: "https://example.com",
    })).toBe("URL");
  });
});
