import type { CategoryKey } from "./types";

export const EXE_MAP: Record<string, CategoryKey> = {
    "chrome.exe": "browser",
    "firefox.exe": "browser",
    "msedge.exe": "browser",
    "brave.exe": "browser",
    "opera.exe": "browser",
    "vivaldi.exe": "browser",
    "arc.exe": "browser",
    "wechat.exe": "office",
    "dingtalk.exe": "office",
    "feishu.exe": "office",
    "telegram.exe": "office",
    "discord.exe": "office",
    "qq.exe": "office",
    "steam.exe": "gaming",
    "epicgameslauncher.exe": "gaming",
    "wegame.exe": "gaming",
    "obs64.exe": "design",
    "obs32.exe": "design",
    "potplayer.exe": "media",
    "potplayer64.exe": "media",
    "vlc.exe": "media",
    "ollama.exe": "ai",
    "code.exe": "development",
    "devenv.exe": "development",
    "idea64.exe": "development",
    "pycharm64.exe": "development",
    "webstorm64.exe": "development",
    "goland64.exe": "development",
    "clion64.exe": "development",
    "rider64.exe": "development",
    "datagrip64.exe": "development",
    "cursor.exe": "development",
    "windsurf.exe": "development",
    "trae.exe": "development",
    "notion.exe": "office",
    "obsidian.exe": "office",
    "typora.exe": "office",
    "word.exe": "office",
    "excel.exe": "office",
    "powerpnt.exe": "office",
    "outlook.exe": "office",
    "photoshop.exe": "design",
    "illustrator.exe": "design",
    "figma.exe": "design",
    "blender.exe": "design",
    "7z.exe": "system",
    "winrar.exe": "system",
    "wps.exe": "office",
};

export function lookupExeMap(exeName: string): CategoryKey | null {
    return EXE_MAP[exeName.toLowerCase()] ?? null;
}
