import type { CategoryRule } from "./types";

export const CATEGORY_RULES: CategoryRule[] = [
    {
        key: "browser",
        name: "浏览器",
        description: "网页浏览工具",
        exactTerms: ["浏览器", "browser"],
        keywords: ["chrome", "firefox", "edge", "safari", "opera", "brave", "vivaldi", "arc"],
        publisherKeywords: ["google", "mozilla", "microsoft edge", "brave software", "vivaldi"],
    },
    {
        key: "development",
        name: "开发工具",
        description: "编程IDE、编辑器、终端、版本控制、硬件调试",
        exactTerms: ["开发", "ide", "编辑器", "终端", "编译器"],
        keywords: [
            "visual studio", "vscode", "intellij", "pycharm", "webstorm", "goland", "clion", "rider", "datagrip",
            "terminal", "git", "docker", "node", "python", "java", "rust", "cargo", "npm", "yarn", "cursor", "windsurf",
            "trae", "hbuilder", "finalshell", "navicat", "sourcetree", "xshell", "tabby", "bun", "nvm",
            "cmake", "pgadmin", "redis desktop", "mu editor", "blend for visual studio", "微信开发者工具",
            "powershell", "pwsh", "cmd", "nsight", "cuda", "nvidia", "redis", "sql shell",
        ],
        pathKeywords: ["jetbrains", "microsoft visual studio", "python3", "nodejs", "docker", "cygwin", "git", "nvidia corporation", "cuda"],
        publisherKeywords: ["jetbrains", "microsoft visual studio", "github", "docker", "git for windows", "python software", "dlang", "atlassian", "nvidia"],
    },
    {
        key: "design",
        name: "设计创作",
        description: "图像编辑、3D建模、UI设计",
        exactTerms: ["设计", "photoshop", "illustrator", "figma", "blender"],
        keywords: [
            "adobe", "photoshop", "illustrator", "figma", "sketch", "blender", "after effects", "premiere",
            "canva", "coreldraw", "audition", "creative cloud", "uxp webview",
        ],
        pathKeywords: ["adobe"],
        publisherKeywords: ["adobe systems", "blender foundation", "figma", "canva"],
    },
    {
        key: "office",
        name: "办公沟通",
        description: "办公套件、即时通讯、邮件、会议、语音",
        exactTerms: ["办公", "聊天", "邮件", "会议", "语音"],
        keywords: [
            "word", "excel", "powerpoint", "outlook", "wechat", "微信", "qq", "钉钉", "飞书",
            "telegram", "discord", "slack", "teams", "notion", "obsidian", "wps",
            "腾讯会议", "tencent meeting", "kook", "印象笔记", "typora",
            "oopz", "mumble", "teamspeak",
        ],
        pathKeywords: ["tencent", "dingtalk", "feishu", "microsoft office", "wemeet", "kook"],
        publisherKeywords: ["tencent", "microsoft corporation", "slack", "notion labs", "obsidian", "atlassian", "wps"],
    },
    {
        key: "gaming",
        name: "游戏平台",
        description: "游戏启动器、游戏平台、对战平台",
        exactTerms: ["游戏", "steam", "epic"],
        keywords: [
            "steam", "epic", "wegame", "gog", "origin", "ubisoft", "battle.net", "xbox",
            "ea launcher", "ea app", "ealauncher", "redlauncher",
            "left 4 dead", "三角洲行动", "无畏契约", "civilization", "infinitode",
            "plain craft launcher", "spell brigade", "minecraft",
            "5e对战平台", "5e client", "完美世界竞技平台",
        ],
        pathKeywords: ["steam", "epic games", "wegame", "ubisoft game launcher", "cd projekt red", "5eplay", "完美世界"],
        publisherKeywords: ["valve", "epic games", "riot games", "ubisoft", "blizzard", "electronic arts", "cd projekt red"],
    },
    {
        key: "game_booster",
        name: "游戏加速器",
        description: "游戏网络加速、帧率优化与游戏性能辅助",
        exactTerms: ["加速器", "booster"],
        keywords: [
            "uu加速器", "uu_launcher", "雷神加速器", "leigod", "ak加速器", "watt toolkit", "steam++",
            "game pp", "游戏加加", "帧率救星", "lossless scaling", "verykuai", "verykuai vk",
            "anti-cheat", "anticheatexpert",
        ],
        pathKeywords: ["gamepp", "game pp", "lossless scaling", "leigod", "uu", "akplatform"],
        publisherKeywords: ["netease", "leigod", "ak"],
    },
    {
        key: "media",
        name: "影音播放",
        description: "视频播放器、音乐播放器、录音",
        exactTerms: ["播放器", "音乐", "视频"],
        keywords: [
            "vlc", "potplayer", "spotify", "foobar", "aimp", "musicbee",
            "netease cloud", "qq音乐", "网易云音乐", "lx music", "lx-music",
            "fxsound", "audacity", "voicemeeter", "maono link",
            "15 bands graphic eq", "8x8 output matrix", "macro buttons",
            "vban", "handbrake",
        ],
        pathKeywords: ["voicemeeter", "cloudmusic", "lx-music", "落雪播放器"],
        publisherKeywords: ["video lan", "kakao", "spotify", "fxsound", "audacity"],
    },
    {
        key: "system",
        name: "系统工具",
        description: "文件管理、系统优化、压缩解压、安全软件",
        exactTerms: ["系统", "管理", "优化", "安全"],
        keywords: [
            "7-zip", "winrar", "ccleaner", "everything", "total commander", "poweriso", "rufus",
            "360驱动大师", "分区助手", "diskm", "dism++", "图吧工具箱",
            "pixpin", "utools", "mem reduct", "process lasso", "easyuefi",
            "latencymon", "rpi imager", "raspberry pi imager",
            "火绒", "huorong", "hips",
        ],
        pathKeywords: ["utilities", "security", "aomei", "dism++", "图吧", "huorong"],
        publisherKeywords: ["7-zip", "rarlab", "voidtools", "360", "aomei"],
    },
    {
        key: "cloud",
        name: "云存储下载",
        description: "网盘、下载工具、文件传输",
        exactTerms: ["下载", "网盘", "云"],
        keywords: [
            "baidu netdisk", "qbittorrent", "thunder", "迅雷", "idm", "motrix", "transmission",
            "onedrive", "dropbox", "google drive",
            "阿里云盘", "夸克网盘", "localsend", "weiyun", "weiyunapp",
        ],
        pathKeywords: ["thunder", "baidunetdisk", "quark", "localsend", "weiyun"],
        publisherKeywords: ["baidu", "dropbox", "alibaba", "localsend"],
    },
    {
        key: "remote",
        name: "远程连接",
        description: "远程桌面、协助和设备共享",
        exactTerms: ["远程"],
        keywords: ["todesk", "rustdesk", "anydesk", "parsec", "向日葵", "向日葵远程控制"],
        pathKeywords: ["rustdesk", "todesk"],
        publisherKeywords: ["todesk", "rustdesk"],
    },
    {
        key: "network",
        name: "网络代理",
        description: "代理、网络切换与通道管理",
        exactTerms: ["代理", "抓包", "wireshark"],
        keywords: ["clash", "nekoray", "shadowsocks", "v2ray", "trojan", "sing-box", "watt toolkit", "wireshark"],
        pathKeywords: ["clash", "nekoray", "wireshark"],
        publisherKeywords: [],
    },
    {
        key: "ai",
        name: "AI 工具",
        description: "大语言模型、AI助手",
        exactTerms: ["ai", "chatgpt", "claude", "ollama"],
        keywords: ["ollama", "chatgpt", "claude", "gemini", "copilot", "midjourney", "stable diffusion"],
        publisherKeywords: ["openai", "anthropic", "ollama"],
    },
    {
        key: "emulator",
        name: "模拟器",
        description: "安卓模拟器与多开相关工具",
        exactTerms: ["模拟器", "多开"],
        keywords: ["雷电", "逍遥", "mumu", "ldplayer", "memu", "夜神", "蓝叠", "android emulator"],
        pathKeywords: ["leidian", "ldmutiplayer", "ldplayer", "microvirt", "memu", "nox"],
    },
    {
        key: "component",
        name: "系统组件",
        description: "运行库、SDK、后台服务、安装程序",
        exactTerms: ["runtime", "redistributable", "sdk"],
        keywords: [
            "runtime", "redistributable", "sdk", "driver", "update helper",
            "vc_redist", "directx", ".net framework", "webview2", "webview",
            "unins000", "uninstall", "setup",
        ],
        pathKeywords: ["redistributable", "runtime", "driver", "sdk", "package cache"],
    },
    {
        key: "other",
        name: "其他",
        description: "未分类软件",
    },
];

export const CATEGORY_BY_KEY = new Map<string, CategoryRule>(
    CATEGORY_RULES.map(rule => [rule.key, rule])
);

export const FALLBACK_CATEGORY = CATEGORY_BY_KEY.get("other")!;
