// Auto-generated by scripts/generate-solar-icons.cjs
// Icon: ClockCircle (clock-circle) · weights: Bold, LineDuotone, Linear
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createIcon } from '../runtime';

export const ClockCircle = /*#__PURE__*/ createIcon('clock-circle', {
  Bold: [[`path`,{d:`M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z`,fill:`currentColor`}],[`path`,{"fill-rule":`evenodd`,"clip-rule":`evenodd`,d:`M12 7.25C12.4142 7.25 12.75 7.58579 12.75 8V11.6893L15.0303 13.9697C15.3232 14.2626 15.3232 14.7374 15.0303 15.0303C14.7374 15.3232 14.2626 15.3232 13.9697 15.0303L11.4697 12.5303C11.329 12.3897 11.25 12.1989 11.25 12V8C11.25 7.58579 11.5858 7.25 12 7.25Z`,fill:`white`}]],
  LineDuotone: [[`circle`,{opacity:`0.5`,cx:`12`,cy:`12`,r:`10`,stroke:`currentColor`,"stroke-width":`1.5`}],[`path`,{d:`M12 8V12L14.5 14.5`,stroke:`currentColor`,"stroke-width":`1.5`,"stroke-linecap":`round`,"stroke-linejoin":`round`}]],
  Linear: [[`circle`,{cx:`12`,cy:`12`,r:`10`,stroke:`currentColor`,"stroke-width":`1.5`}],[`path`,{d:`M12 8V12L14.5 14.5`,stroke:`currentColor`,"stroke-width":`1.5`,"stroke-linecap":`round`,"stroke-linejoin":`round`}]]
});
