// Auto-generated by scripts/generate-solar-icons.cjs
// Icon: Mouse (mouse) · weights: Bold, LineDuotone, Linear
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createIcon } from '../runtime';

export const Mouse = /*#__PURE__*/ createIcon('mouse', {
  Bold: [[`path`,{d:`M19 8.97414V14.9861C19 18.8598 15.866 22 12 22C8.13401 22 5 18.8598 5 14.9861V8.97414C5 5.35433 7.73668 2.37497 11.25 2V5.38542C10.6588 5.66685 10.25 6.27067 10.25 6.97016V8.97414C10.25 9.94256 11.0335 10.7276 12 10.7276C12.9665 10.7276 13.75 9.94256 13.75 8.97414V6.97016C13.75 6.27067 13.3412 5.66685 12.75 5.38542V2C16.2633 2.37497 19 5.35433 19 8.97414Z`,fill:`currentColor`}]],
  LineDuotone: [[`path`,{d:`M5 9C5 5.13401 8.13401 2 12 2C15.866 2 19 5.13401 19 9V15C19 18.866 15.866 22 12 22C8.13401 22 5 18.866 5 15V9Z`,stroke:`currentColor`,"stroke-width":`1.5`}],[`path`,{d:`M10.5 8.5C10.5 7.67157 11.1716 7 12 7C12.8284 7 13.5 7.67157 13.5 8.5V10.5C13.5 11.3284 12.8284 12 12 12C11.1716 12 10.5 11.3284 10.5 10.5V8.5Z`,stroke:`currentColor`,"stroke-width":`1.5`}],[`path`,{opacity:`0.5`,d:`M12 2V7`,stroke:`currentColor`,"stroke-width":`1.5`,"stroke-linecap":`round`}]],
  Linear: [[`path`,{d:`M5 9C5 5.13401 8.13401 2 12 2C15.866 2 19 5.13401 19 9V15C19 18.866 15.866 22 12 22C8.13401 22 5 18.866 5 15V9Z`,stroke:`currentColor`,"stroke-width":`1.5`}],[`path`,{d:`M10.5 8.5C10.5 7.67157 11.1716 7 12 7C12.8284 7 13.5 7.67157 13.5 8.5V10.5C13.5 11.3284 12.8284 12 12 12C11.1716 12 10.5 11.3284 10.5 10.5V8.5Z`,stroke:`currentColor`,"stroke-width":`1.5`}],[`path`,{d:`M12 2V7`,stroke:`currentColor`,"stroke-width":`1.5`,"stroke-linecap":`round`}]]
});
